### ISSUE TITLE
Make an easy way to update a single entry

### ISSUE THREAD

**Issue by ChristopherKiss** [Colonise/DataSource#24]
`.update(entry: TEntry, updates: { [TKey in keyof TEntry]: TEntry[TKey]; }): number`

`.assign(index: number, entry: TEntry): TEntry[]`

**Comment by pathurs** [comment]
I've only added `.assign(index: number, entry: TEntry): TEntry[]`.

The reason is that the entries themselves are still fully accessible, and can be assigned to as needed.
